### ISSUE TITLE
Duplicate Contacts - Same IP, Different Name

### ISSUE THREAD

**Issue by rmccorm4** [ajstensland/slyther#10]
Upon creating a contact, we should check if an IP already exists in the contact book, or either prompt user to update the contact, or redirect them to an `update` command:
```
> lc
---------- CONTACTS LIST ----------
AJ
IP: 127.0.0.1
Fingerprint: None

me
IP: 127.0.1.1
Fingerprint: None

blah
IP: 127.0.0.1
Fingerprint: None
```

**Comment by ajstensland** [comment]
Currently solved in branch `contact-rework`, but this revealed a couple more bugs.
